import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'Nova Fitness',
    short_name: 'Nova',
    description: 'Nova fitness center',
    start_url: '/',
    display: 'standalone',
    background_color: '#ffffff',
    theme_color: '#ffffff',
    icons: [
      // Generated by pwa-asset-generator
      {
        src: '/manifest-icon-192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any'
      },
      {
        src: '/manifest-icon-512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any'
      },
      // Optional: include favicon for older browsers
      {
        src: '/favicon-196.png',
        sizes: '196x196',
        type: 'image/png',
        purpose: 'any'
      },
      // Optional: Apple touch icon (though usually linked separately in <head>)
      {
        src: '/apple-icon-180.png',
        sizes: '180x180',
        type: 'image/png',
        purpose: 'any'
      }
    ]
  }
}